/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./src/components/layout/AppLayout.vue')['default']
    BottomBar: typeof import('./src/components/workspace/BottomBar.vue')['default']
    CanvasArea: typeof import('./src/components/workspace/CanvasArea.vue')['default']
    CanvasToolbar: typeof import('./src/components/workspace/CanvasToolbar.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElementPanel: typeof import('./src/components/sidebar/ElementPanel.vue')['default']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    GridLayer: typeof import('./src/components/canvas/GridLayer.vue')['default']
    MapList: typeof import('./src/components/sidebar/MapList.vue')['default']
    NodeElement: typeof import('./src/components/canvas/NodeElement.vue')['default']
    NodeSelect: typeof import('./src/components/ui/NodeSelect.vue')['default']
    Panel: typeof import('./src/components/common/Panel.vue')['default']
    PathFormDialog: typeof import('./src/components/dialogs/PathFormDialog.vue')['default']
    PathLineElement: typeof import('./src/components/canvas/PathLineElement.vue')['default']
    PropertiesPanel: typeof import('./src/components/properties/PropertiesPanel.vue')['default']
    WorkspaceHeader: typeof import('./src/components/workspace/WorkspaceHeader.vue')['default']
  }
}
